# vim: ft=yaml
---
driver:
  name: vagrant
  customize:
    memory: 512
  vm_hostname: postfix.ci.local

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  formula: postfix
  log_level: info
  state_top:
    base:
      "*":
        - postfix
  pillars:
    top.sls:
      base:
        "*":
          - postfix
    postfix.sls:
      server:
        ssl:
          enabled: false

platforms:
  - name: bento/ubuntu-14.04
#  - name: bento/ubuntu-16.04
#  - name: bento/centos-7.1

suites:

  - name: server
    provisioner:
      pillars-from-files:
        postfix.sls: tests/pillar/server.sls
    driver:
      hostname: postfix.ci.local

  - name: relay
    provisioner:
      pillars-from-files:
        postfix.sls: tests/pillar/relay.sls

  - name: backupmx
    provisioner:
      pillars-from-files:
        postfix.sls: tests/pillar/backupmx.sls
