---
# https://docs.chef.io/config_yml_kitchen.html

driver:
    # OPENSTACK API
    # https://github.com/test-kitchen/kitchen-openstack
    name: openstack
    # auth
    openstack_auth_url: <%= ENV['OS_AUTH_URL'] %>/tokens
    openstack_username: <%= ENV['OS_USERNAME'] || 'ci' %>
    openstack_api_key:  <%= ENV['OS_PASSWORD'] || 'ci' %>
    openstack_tenant:   <%= ENV['OS_TENANT_NAME'] || 'ci_jenkins' %>
    # openstack_api_key:  <%= ENV['OS_AUTH_TKN'] %>
    # "#{ENV['OS_TENANT_NAME']}"
    # "#{ENV['OS_REGION_NAME']}"
    # vm

    #floating_ip_pool: <%= ENV['OS_FLOATING_IP_POOL'] || 'nova' %>
    #key_name: <%= ENV['BOOTSTRAP_SSH_KEY_NAME'] || 'pmi_id_ed25519' %>
    key_name: <%= ENV['BOOTSTRAP_SSH_KEY_NAME'] || 'bootstrap_insecure' %>
    private_key_path: <%= ENV['BOOTSTRAP_SSH_KEY_PATH'] || "#{ENV['HOME']}/.ssh/id_rsa_bootstrap_insecure" %>

    #require_chef_omnibus: true         #[e.g. 'true' or a version number if you need Chef]


    ## EC2 API
    # name: ec2
    # https://github.com/test-kitchen/kitchen-ec2
    # aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    # aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    # aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>

platforms:
    - name: ubuntu-14.04
      driver:
        username: root
        image_ref: ubuntu-14-04-x64-1455869035
        flavor_ref: m1.medium
        #openstack_network_name: tcp_dev_pmi
        network_ref:
          - ci-net
      # force update apt cache on the image
      run_list:
        - recipe[apt]
      attributes:
        apt:
            compile_time_update: true
transport:
  username: root


# vim: sw=2 ts=2 sts=2 tw=125
## EXAMPLES, dynamic kitchen driver, http://stackoverflow.com/questions/26516373/alternate-drivers-with-test-kitchen
